### ISSUE TITLE
Missing prisma-cloud-go clone instruction for setup

### ISSUE THREAD

**Issue by zimmermanc** [PaloAltoNetworks/terraform-provider-prismacloud-orig#1]
## Documentation link

https://github.com/PaloAltoNetworks/terraform-provider-prismacloud/blob/master/README.md

## Describe the problem
~/go/src/github.com/terraform-providers/terraform-provider-prismacloud$ make build
==> Checking that code complies with gofmt requirements...
go install
go: github.com/paloaltonetworks/prisma-cloud-go@v0.0.0-20200327180535-f648dce6b742: parsing ../prisma-cloud-go/go.mod: open /home/zimmermanc/go/src/github.com/terraform-providers/prisma-cloud-go/go.mod: no such file or directory
GNUmakefile:9: recipe for target 'build' failed
make: *** [build] Error 1

## Suggested fix

Add 
git clone https://github.com/PaloAltoNetworks/prisma-cloud-go.git

**Comment by shinmog** [comment]
@zimmermanc 

This is a temporary issue because of the redirect in the go.mod file that assumes you've `git clone`ed the prisma-cloud-go repo, and they share the same parent directory.  When this is ready to be released, dependencies will be vendor'ed in, so this won't be an issue.  :)

**Comment by shinmog** [comment]
Dependencies are now vendored in, closing this issue.
