### ISSUE TITLE
provider provider.prismacloud does not support resource type

### ISSUE THREAD

**Issue by zimmermanc** [PaloAltoNetworks/terraform-provider-prismacloud-orig#10]
## Describe the bug

terraform plan fails with error 
## Expected behavior

terraform plan completes successfully

## Current behavior

Using the documentation example fails

resource "prismacloud_compliance_standard" "example" {
    name = "Foo"
    description = "Made by Terraform"
}

Error: Invalid resource type

  on prisma.tf line 21, in resource "prismacloud_compliance_standard" "example":
  21: resource "prismacloud_compliance_standard" "example" {

The provider provider.prismacloud does not support resource type
"prismacloud_compliance_standard".

## Steps to reproduce

1.
2.
3.
4.

## Your Environment

go version go1.14.1 linux/amd64
Terraform v0.12.24
+ provider.prismacloud (unversioned)

**Comment by shinmog** [comment]
This was determined to be an environment issue.  The provider was built and available locally.  Deleting the locally built provider allowed `terraform init` to download the provider, at which point this issue went away.
