### ISSUE TITLE
Errors in readme.md file

### ISSUE THREAD

**Issue by rajcheval** [PaloAltoNetworks/terraform-provider-prismacloud-orig#2]
## Documentation link

https://github.com/PaloAltoNetworks/terraform-provider-prismacloud/blob/master/README.md

## Describe the problem

It says
git clone git@github.com:terraform-providers/terraform-provider-prismacloud
but this repo does not exist.

It says 
See the Palo Alto Networks Prisma Cloud Provider documentation to get started using the provider. It refers to link https://www.terraform.io/docs/providers/prismacloud/index.html which does not exist.

## Suggested fix

Include the link to correct github repo and correct documentation link

**Comment by shinmog** [comment]
Thanks for catching this; but it's just a temporary difference in where the provider lives now vs where it will live once it's finished going through the certification process.
