### ISSUE TITLE
Publish provider to terraform provider registry 

### ISSUE THREAD

**Issue by mwarkentin** [PaloAltoNetworks/terraform-provider-prismacloud-orig#4]
### Is your feature request related to a problem?

Terraform 0.13 enables 3rd party providers to be installed directly from the Terraform Registry. We are interested in experimenting with this provider and installing it that way would be nicer than installing manually as a plugin.

Here's an example on another 3rd party provider: https://github.com/jianyuan/terraform-provider-sentry/issues/74#issue-635410065

```
👋 Hi, I'm on the Terraform Providers team at HashiCorp. With the release of the Terraform 0.13 beta, users can now download and install community providers from the registry. We are inviting provider authors (especially those for popular community providers) to publish their providers in a closed beta.

To get invited to the closed beta, please email terraform-registry-beta@hashicorp.com. We need:

    A list of GitHub usernames to add to the beta (you and any team members who will publish)
    List of provider repositories you plan to publish
    A GPG public key in ASCII-armor format, which you will be using to sign your provider releases

You can use one key for all of your providers, or separate keys if you prefer. If you are publishing from an organization, this key or keys will be associated with that namespace. Once in the beta, you can manage personal keys in the UI as well.
```

### Describe the solution you'd like

I can configure and install the prismacloud provider as easily as any native provider directly through my `.tf` configuration.

**Comment by shinmog** [comment]
This provider is currently going through the certification process, which will allow it to be retrieved automatically via `terraform init`.

**Comment by shinmog** [comment]
This is now published on (what is now) the classic provider ecosystem:

https://www.terraform.io/docs/providers/prismacloud/index.html

https://github.com/terraform-providers/terraform-provider-prismacloud

The new registry system HashiCorp is implementing for Terraform 0.13 still needs to have this (and the panos provider) added to it, but I'm going to close this issue out as it has addressed the "this provider needs to be more officially available" issue.
